# Site settings
title: Mauricio Jost
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mauriciojost.github.io" # the base hostname & protocol for your site
github_username:  mauriciojost
include: ["reveal.js"]

# Build settings
sass:
  style: :compressed
markdown: redcarpet
redcarpet:
  extensions: ["strikethrough", "with_toc_data"]
